sudo: required

services:
 - docker

before_script:
  - pip install --user docker-squash

script:
  - travis_retry timeout 540 docker pull $(sed -n '1s/FROM //p' ./Dockerfile) | cat
  - travis_retry docker build -t ${TRAVIS_REPO_SLUG}:latest .

after_success:
  - BASE_IMAGE="$(sed -n '1s/FROM //p' ./Dockerfile)"
#  - travis_wait 30 ~/.local/bin/docker-squash -f "${BASE_IMAGE}" "${TRAVIS_REPO_SLUG}:latest"
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} = master ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:latest";
   fi

branches:
  only:
  - master
