name: test-environment
channels:
  - conda-forge
dependencies:
  - python == 3.7
  - scipy
  - numpy 
  - matplotlib 
  - flake8
  - sphinx
  - cython
  - graphviz
  - pytest
  - pytest-cov
  - sphinxcontrib-bibtex
  - pint
  - pip
  - cvxopt
  - pyyaml
  - pylint
