name: test-environment
channels:
  - conda-forge
dependencies:
  - python = 3.7
  - scipy >= 1.2
  - numpy
  - matplotlib
  - flake8
  - sphinx
  - cython
  - graphviz
  - pytest
  - pytest-cov
  - sphinxcontrib-bibtex
  - pint
  - pip
  - cvxopt
  - pyyaml